### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by playground** [IjzerenHein/node-web-bluetooth#11]
I just bought a wise orchard device to control watering my garden.  I want to set up a raspberry pie to manage the device to control the unit.  Can you help explain the difference between this and https://www.npmjs.com/package/node-bluetooth?  I assume with this I would Abe to control watering schedule when the condition is met?

**Comment by IjzerenHein** [comment]
Simply put, this one follows the web-bluetooth spec https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API
So any code you write with this will also work in the browser and vice versa
