### ISSUE TITLE
docs inaccurate

### ISSUE THREAD

**Issue by salutuj** [IjzerenHein/node-web-bluetooth#2]
hi please update the documentation section on npm site:
https://www.npmjs.com/package/node-web-bluetooth
Usage
    const server = await device.connect();

When i try sample in section Programmatically selecting a device it does not work. 
(node:2928) UnhandledPromiseRejectionWarning: TypeError: device.connect is not a function

It must be a gatt property mehod:
    const server = await device.gatt.connect();

**Comment by IjzerenHein** [comment]
Thanks for the heads up. I've updated it.
Cheers
