### ISSUE TITLE
Can't establish Notifications

### ISSUE THREAD

**Issue by decurus** [IjzerenHein/node-web-bluetooth#4]
Hello there,
I am currently working  on establishing a connection between a device and the computer. whenever the device changes its state, the computer shall be notified. On my way i noticed a strange behavior.
Connecting to the server yields no problem and console.log(server) shows that indeed the device seems to be connected. However:
`const service await server.getPrimaryService(UUID);`
allways returns, that the service UUID is not found, though i am really sure, that i entered the correct uuid and indeed, using getPrimaryServices and listing them, shows, that the id of the service i want to use is correct.
however: 
i tried the following:
`const services = server.getPrimaryServices();
var service = service[3] //3 beeing the service I want to use`
this way i can see the service-characteristics. However: the same thing as with the services happens. I cant use getCharacteristic(UUID);, it returns, that the UUID is not found, but storing it in an array and getting it from there seems to work, at least i can see some results using characteristic.readValue();
But the main problem that caused me to write this issue is: using 
`await char.startNotifications();`
does not seem to do anything. 
the execution seems to get stuck at this point. No error message and the code does not run into the catch blog.
And from here on out i don't really know what to do.
I will attach a snippet of the (shortend) code of the project:

```
const Bluetooth = require(\'node-web-bluetooth\')

const device = Bluetooth.requestDevice({
  delegate: new Bluetooth.InteractiveRequestDeviceDelegate({
    header: 'Select device',
    format: (device) => \`${device.id} - ${device.name}\`
  })
}).then(function(bluetoothDevice) {
  connect(bluetoothDevice);
})

async function connect(deviceToConnect) {
  try {
    const server = await deviceToConnect.gatt.connect().catch((err) => {
      console.log(err);
    });

const service = await server.getPrimaryServices().catch((err) => {console.log(err);});
const characteristics = await service[3].getCharacteristics().catch((err) => {console.log(err);});
var char = characteristics[0];
await char.startNotifications();  //Nothing after this line is beeing called
console.log('\n----STARTED----');}
catch (e) {
console.log(e)}
}
```

I am working on ubuntu 18 and my node version is v8.10.0. There are no other dependencies in the project. I am running with sudo (the package doesn't seem to allow otherwise anyways)
Have a nice one
Benny

**Comment by IjzerenHein** [comment]
Hi. I'm not sure I can help here, but I'll try to share some insight. This lib is really just a thin layer on top on the noble library, and implements the web-bluetooth on top of that.
Looking at the `startNotifications` function reveals that it just calls `subscribe` on the noble characteristic and returns the result in promisified form.
It could be that the problem is in the linux noble implementation, or it might even be in the device that you are connecting to. Is that something you implemented yourself?
cheers,
Hein
